# Generated by Django 3.1.7 on 2021-04-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='user',
        ),
    ]
