# Generated by Django 3.1.7 on 2021-04-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210404_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(0, 'Decline'), (1, 'Accept'), (2, 'Tentative')], default=2, max_length=1)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dog')),
                ('playdate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.playdate')),
            ],
        ),
    ]
