# Generated by Django 3.1.7 on 2021-04-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='response',
            field=models.IntegerField(choices=[(0, 'Decline'), (1, 'Accept'), (2, 'Tentative')], default=2),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dog')),
            ],
        ),
    ]
