# Generated by Django 3.1.7 on 2021-04-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210405_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdate',
            name='time',
            field=models.CharField(choices=[(0, '6:00am'), (1, '6:30am'), (2, '7:00am'), (3, '7:30am'), (4, '8:00am'), (5, '8:30am'), (6, '9:00am'), (7, '9:30am')], default=(3, '7:30am'), max_length=7),
        ),
    ]
