# Generated by Django 3.1.7 on 2021-04-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210405_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playdate',
            name='time',
            field=models.CharField(choices=[('0', '6:00am'), ('1', '6:30am'), ('2', '7:00am'), ('3', '7:30am'), ('4', '8:00am'), ('5', '8:30am'), ('6', '9:00am'), ('7', '9:30am'), ('8', '10:00am'), ('9', '10:30am'), ('10', '11:00am'), ('11', '11:30am'), ('12', '12:00pm'), ('13', '12:30m'), ('14', '1:00pm'), ('15', '1:30pm'), ('16', '2:00pm'), ('17', '2:30pm'), ('18', '3:00pm'), ('19', '3:30pm'), ('20', '4:00pm'), ('21', '4:30pm'), ('22', '5:00pm'), ('23', '5:30pm'), ('24', '6:00pm'), ('25', '6:30pm'), ('26', '7:00pm'), ('27', '7:30pm'), ('28', '8:00pm'), ('29', '8:30pm'), ('30', '9:00pm'), ('31', '9:30pm'), ('32', '10:00pm')], default=('14', '1:00pm'), max_length=7),
        ),
    ]
